### ISSUE TITLE
Privacy Policy link is broken on Google Marketplace listing

### ISSUE THREAD

**Issue by heyalistair** [evbacher/gd2md-html#127]
When I try to click on the link from the Marketplace listing, I see a Google Sites page that says
```
We're sorry, we were unable to locate the site /edbacher/home/gd2md-html-privacy-policy.
```

The broken link is:
```
https://sites.google.com/site/edbacher/home/gd2md-html-privacy-policy
```

**Comment by mb** [comment]
Looking at the [README.md](https://github.com/evbacher/gd2md-html/tree/ad31b543d58c97248cca78c14fa6e6ed6ceb85e3#installation-and-other-details), there seems to exist a privacy policy at https://github.com/evbacher/gd2md-html/wiki/Privacy-policy. Do you mind updating the link on https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607? That would be really helpful for me, due to company restrictions. It needs at least privacy/security policy to get through security review. Otherwise, it won't be whitelisted in the Google Workspace. Thanks so much!

**Comment by evbacher** [comment]
I've added a link to the privacy policy on the add-on listing. The new URL is https://beanroad.com/docs-to-markdown/privacy.html. I'll change that in the README too.
