### ISSUE TITLE
[BUG:] Extra line spaces are not converted

### ISSUE THREAD

**Issue by sevenshamrocks** [evbacher/gd2md-html#153]
When converting to Markdown or HTML, any extra line breaks in the doc aren't carried over. 

"line 1"
 

line 2"

Becomes 

"Line 1

Line 2"

It would be great to add <p>&nbsp;</p> or something similar to get the line breaks when converting. 

Thanks.

**Comment by evbacher** [comment]
Do you mean that 

line1

line 2

becomes

line 1
line 2

?

If not, can you link to a doc (view only permission is fine) that demonstrates the problem?

We currently do not convert empty lines (unless they're in code blocks.

**Comment by sevenshamrocks** [comment]
Ha. Extra line breaks weren't preserved here. Yes. That's essentially what I mean. 

If it's not in the plan to support, would you mind giving me a tip on where I can add to a custom fork? What would be the section reading blank lines?

**Comment by evbacher** [comment]
I don't think we're going to implement this in Docs to Markdown. Since HTML ignores blank lines, we don't want to insert `<br>` or `<p>` whenever there's an empty line in the Google Doc. Many of us (myself included) add a blank line between paragraphs in a Google Doc. But each newline officially starts a paragraph in a Google Doc, so there would be a lot of extra `<p>`s. I think you found the code in md.handleParagraph().
