### ISSUE TITLE
Is there a way to use this addon's functionality in the server side?

### ISSUE THREAD

**Issue by tanvibhakta** [evbacher/gd2md-html#21]
Hey, I am wondering if we can do just what the title says. I can't seen to be able to use the code from the html file you've provided in the repo, unless I'm missing something major about how a gdocs add on works? 
I would have liked to email you about this to be honest, I don't think an issue board is the right place to discuss this. It would be great if we could exchange emails to continue discussing this.

**Comment by evbacher** [comment]
Do you mean you can't use the HTML after converting your Google Doc? I'm not sure exactly what your problem is. This add-on is primarily designed to convert a Google Doc to Markdown (though it also supports conversion to HTML).

There's a mailing list at https://groups.google.com/forum/#!forum/gd2md-html that we could discuss this on. There may be others with some ideas about this as well.

**Comment by evbacher** [comment]
Closing this for now -- will follow up via email.
