### ISSUE TITLE
In Markdown, underlined text becomes HTML-tagged, instead of wrapped in *emphasis characters*

### ISSUE THREAD

**Issue by bland328** [evbacher/gd2md-html#28]
I suggest/request that when converting to Markdown, underlined text should be wrapped in \*single asterisks\*.

I _want_ to suggest single underscores, because they visually resemble underlining so strongly, but I'm instead suggesting single asterisks, because:

1.  It _(unscientifically, admittedly)_ appears _so_ very common to me that underscores are used to indicate _italics_--including right here in GitHub posts.

2. Making it single asterisks instead of single underscores provides a distinct mapping that, though it will likely be rendered the same as if it were underscores, can survive a round-trip conversion.

For those who aren't familiar, the [Markdown syntax document](https://daringfireball.net/projects/markdown/syntax#em) simply asserts that wrapping in a single emphasis character (whether \*asterisks\* _or_ \_underscores\_) should result in \<em> tags when generating HTML, while wrapping in doubled-up emphasis characters (again, \*\*double-asterisks\*\* _or_ \_\_double-underscores\_\_) should result in \<strong> HTML tags.

**Comment by bland328** [comment]
_That_ being said, after writing the above, I then promptly used two Markdown editors which both render:

- \*\*This as bold\*\*
- \*This as italic\*
- \_This as underlined\_

So, now, I would argue for that, though I recognize plenty would likely argue otherwise 😅

**Comment by evbacher** [comment]
What Markdown editors are you using that render \_underlined\_ as underlined text? It seems like both GitHub and Commonmark (https://commonmark.org/help/) render \_italic\_ as italic text.

In a Google Doc, there is italic text, bold text, and underlined text. Since Markdown already provides for ways to markup italic and bold, GD2md-html uses \_italic\_ and \*\*bold\*\*.

I'm assuming that if someone chooses to underline something in a Google Doc, they really want underlined text, so I'm using some inline CSS to give them that. (I'm not sure how useful it really is in practice, but I don't want to assume that changing underlined text to italic text is the right thing to do.

**Comment by bland328** [comment]
Sorry for the mistake, but I was only half right: I thought Ulysses was doing that, but since I'm just starting to use it, I was fooled when a _global_ change of mode in that software switched from rendering \_underscore-wrapped\_ text as italic to rendering it as underlined.

Highland 2, however--an editor I use frequently--_does_ support \*\*bold\*\*, \*italic\* and \_underlined\_ text.

That all being said, and after more consideration, I return to my original instinct: I vote that it'd be handy if underlined text ended up wrapped in \*single asterisks\*.

Such a change doesn't alter the Markdown you already generate, provides a Markdown-compliant result that "works right out of the box," and yet it is also distinct, in case someone wants to search-and-replace it for a particular purpose.

Thanks for your consideration, and for developing such a great tool!

**Comment by evbacher** [comment]
I'm glad you like this tool!

You're right -- since we're converting italic text to \_italic text\_ and not using single \* for markup now, we could use \*underlined text\* for text that is actually underlined in the Google Doc.

But then text that is actually underlined in the Doc would show up as *underlined text* in the rendered Markdown. I feel like that's a non-obvious side-effect, and perhaps not what the writer intends/wants. I'm trying to keep the conversion pretty literal.

**Comment by bland328** [comment]
I think we're both trying to "keep the conversion pretty literal" from _slightly_ different perspectives.

But, that's kind of a tall order with typography-to-Markdown conversions, since Markdown doesn't support bold, italic, underlined, or any other type styling--it just supports the concept that some text needs to be \<em\>phasized, and sometimes \<strong\>ly.

So, though this conversion is more art _(and convention)_ than science, I'd argue that when converting to Markdown, it is best to get Markdown, and not \<span\>s.

So, I'd say that underlined text could arguably be converted to \*\*this\*\*, \*this\*, \_\_this\_\_ or \_this\_. And that you might as well map it to something you aren't already using.

But I could be wrong--it's happened before 😉

**Comment by evbacher** [comment]
Yeah, the <span> for style is kind of ugly, but certainly permissible in Markdown. We also use some HTML for some mixed code/font areas, and for tables. (Though I'll investigate Markdown for simple tables at some point.)

**Comment by bland328** [comment]
Understood, and thanks for considering and taking the time to discuss! I can, of course, search and replace the \<span\>s to get my desired result.

And, again--thanks for creating this tool.

**Comment by evbacher** [comment]
Thanks for the discussion. To avoid non-obvious side effects, I'm going to leave the current conversion as-is: that is, underlined text in a Google Doc will show up as underlined in the Markdown/HTML conversion. Feel free to reopen if necessary.
