### ISSUE TITLE
HTML conversion adds space into hyperlink incorrectly

### ISSUE THREAD

**Issue by JanineYardley** [evbacher/gd2md-html#46]
To recreate the issue:

- Create a link within a sentence
- Convert to HTML (leaving all options off)
- See the output has added the preceding space into the hyperlink as per the following screenshot:

![Screenshot 2019-07-18 at 10 54 42](https://user-images.githubusercontent.com/8224583/61448293-8b39b600-a94a-11e9-8555-ac2e9f25a036.png)

**Comment by evbacher** [comment]
Do you mean the space between <a and href="http://..."?

That's just broken there naturally because the sidebar is narrow. If you don't select the "Wrap HTML" option, the paragraph will come out as a single line. If you do wrap the HTML, it will often break after the <a because the href="http://..." is often pretty long.

Does the converted HTML render correctly? If there's a problem with that, then we do have a bug, but I haven't seen that yet -- let me know if you do see a problem with the rendered HTML.

**Comment by JanineYardley** [comment]
I'm sorry - after closer examination... the issue is actually with Google Docs.

In the highlighted text in the screenshot, the link starting with 'A Still, Small...' actually starts in the empty space before 'A'. Google Docs sometimes shows the space character with it's underline, but not other times.

Will report to Google. Thanks for getting back to me.
