### ISSUE TITLE
the html and markdown tags for table is incorrect

### ISSUE THREAD

**Issue by ndhulekar** [evbacher/gd2md-html#70]
Create a table in google docs, click the Doc to Markdown add on and  view the output.
The tags are the same for Markdown and HTML and incorrect.

**Comment by evbacher** [comment]
See #22 for more discussion about this issue.

All tables currently get converted to HTML (which is permissible in Markdown), since HTML can handle much more complex tables than Markdown table markup can handle.

If you have any tables, we note in the top comment that your tables will be in HTML (even if you're converting to Markdown.
